default:
  golem_name: inputs
  golem_version: 0.0.0.9000
  app_prod: no
  population_projections:
    principal_proj: "Principal projection"
    var_proj_10_year_migration: "10 year migration trends"
    var_proj_alt_internal_migration: "5 year internal migration trend"
    var_proj_high_intl_migration: "High migration"
    var_proj_low_intl_migration: "Low migration"
    const_fertility_no_mortality_improvement: "Constant fertility = no mortality improvement"
    const_fertility: "Constant fertility"
    high_population: "High population"
    young_age_structure: "Young age structure"
    high_fertility: "High fertility"
    old_age_structure: "Old age structure"
    low_population: "Low population"
    low_fertility: "Low fertility"
    high_life_expectancy: "High life expectancy"
    low_life_expectancy: "Low life expectancy"
    no_mortality_improvement: "No mortality improvement"
    zero_eu_migration: "0% Future EU migration (Not National Statistics)"
    half_eu_migration: "50% Future EU migration (Not National Statistics)"
    zero_net_migration: "Zero net migration (natural change only)"
    replacement_fertility: "Replacement fertility"
  non-demographic_adjustment:
    aae:
      walk-in: [1.0117592, 1.014443]
      ambulance: [1.0117592, 1.014443]
    ip:
      elective: [1.0050266, 1.007375]
      non-elective: [1.0187719, 1.024636]
      maternity: [0.9732562, 0.980959]
    op:
      first: [1.0222222, 1.027585]
      followup: [1.0222222, 1.027585]
      procedure: [1.0222222, 1.027585]
  mitigators_config:
    mitigators_admission_avoidance:
      activity_type: ip
      mitigators_type: activity_avoidance
      y_axis_title: "Admissions per 1,000 population"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.001)
      funnel_x_title: "Catchment Population of Trust"
      funnel_number_type: !expr scales::comma_format()
      slider_scale: 1
      slider_step: 0.001
      strategy_subset:
        alcohol_partially_attributable_acute: "Alcohol Partially Attributable (Acute)"
        alcohol_partially_attributable_chronic: "Alcohol Partially Attributable (Chronic)"
        alcohol_wholly_attributable: "Alcohol Wholly Attributable"
        ambulatory_care_conditions_acute: "Ambulatory Care Conditions (Acute)"
        ambulatory_care_conditions_chronic: "Ambulatory Care Conditions (Chronic)"
        ambulatory_care_conditions_vaccine_preventable: "Ambulatory Care Conditions (Vaccine Preventable)"
        cancelled_operations: "Cancelled Operations"
        eol_care_2_days: "EOL Care (2 Days)"
        eol_care_3_to_14_days: "EOL Care (3 to 14 Days)"
        evidence_based_interventions_ent: "Evidence Based Interventions (ENT)"
        evidence_based_interventions_general_surgery: "Evidence Based Interventions (General Surgery)"
        evidence_based_interventions_gi_surgical: "Evidence Based Interventions (GI Surgical)"
        evidence_based_interventions_msk: "Evidence Based Interventions (MSK)"
        evidence_based_interventions_urology: "Evidence Based Interventions (Urology)"
        evidence_based_interventions_vascular_varicose_veins: "Evidence Based Interventions (Vascular Varicose Veins)"
        falls_related_admissions: "Falls Related Admissions"
        frail_elderly_high: "Frail Elderly (High)"
        frail_elderly_intermediate: "Frail Elderly (Intermediate)"
        intentional_self_harm: "Intentional Self Harm"
        medically_unexplained_related_admissions: "Medically Unexplained Related Admissions"
        medicines_related_admissions_explicit: "Medicines Related Admissions: Explicit"
        medicines_related_admissions_implicit_anti-diabetics: "Medicines Related Admissions: Implicit (Anti Diabetics)"
        medicines_related_admissions_implicit_benzodiasepines: "Medicines Related Admissions: Implicit (Benzodiasepines)"
        medicines_related_admissions_implicit_diurectics: "Medicines Related Admissions: Implicit (Diurectics)"
        medicines_related_admissions_implicit_nsaids: "Medicines Related Admissions: Implicit (NSAIDS)"
        obesity_related_admissions: "Obesity Related Admissions"
        raid_ae: "Raid AE"
        readmission_within_28_days: "Readmission Within 28 Days"
        smoking: "Smoking"
        zero_los_no_procedure_adult: "Zero LOS: No Procedure (Adult)"
        zero_los_no_procedure_child: "Zero LOS: No Procedure (Child)"
    mitigators_mean_los_reduction:
      activity_type: ip
      mitigators_type: efficiencies
      y_axis_title: "Mean Length of Stay (days)"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.1)
      funnel_x_title: "Number of Admissions"
      slider_scale: 1
      slider_step: 0.1
      strategy_subset:
        emergency_elderly: "Emergency Elderly"
        enhanced_recovery_bladder: "Enhanced Recovery (Bladder)"
        enhanced_recovery_breast: "Enhanced Recovery (Breast)"
        enhanced_recovery_colectomy: "Enhanced Recovery (Colectomy)"
        enhanced_recovery_hip: "Enhanced Recovery (Hip)"
        enhanced_recovery_hysterectomy: "Enhanced Recovery (Hysterectomy)"
        enhanced_recovery_knee: "Enhanced Recovery (Knee)"
        enhanced_recovery_prostate: "Enhanced Recovery (Prostate)"
        enhanced_recovery_rectum: "Enhanced Recovery (Rectum)"
        excess_beddays_elective: "Excess Beddays (Elective)"
        excess_beddays_emergency: "Excess Beddays (Emergency)"
        raid_ip: "Raid IP"
        stroke_early_supported_discharge: "Stroke Early Supported Discharge"
      params_items:
        type: "all"
    mitigators_aec_los_reduction:
      activity_type: ip
      mitigators_type: efficiencies
      y_axis_title: "% admissions with a greater than 0-day length of stay"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Admissions"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        ambulatory_emergency_care_low: "Ambulatory Emergency Care: Low"
        ambulatory_emergency_care_moderate: "Ambulatory Emergency Care: Moderate"
        ambulatory_emergency_care_high: "Ambulatory Emergency Care: High"
        ambulatory_emergency_care_very_high: "Ambulatory Emergency Care: Very High"
      params_items:
        type: "aec"
    mitigators_preop_los_reduction:
      activity_type: ip
      mitigators_type: efficiencies
      y_axis_title: "Procedures with a Pre-op LoS (per 1000 operations)"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.1, scale = 1000)
      funnel_x_title: "Number of Procedures Performed"
      slider_scale: 1000
      slider_step: 0.1
      strategy_subset:
        pre-op_los_1-day: "Pre Op LOS (1 Day)"
        pre-op_los_2-day: "Pre Op LOS (2 Day)"
      params_items:
        type: "pre-op"
        pre-op_days:
          pre-op_los_1-day: 1
          pre-op_los_2-day: 2
    mitigators_bads:
      activity_type: ip
      mitigators_type: efficiencies
      y_axis_title: "% of Procedures Performed in Non-Target Setting"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Procedures Performed"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        bads_daycase_occasional: "BADS: Daycase Occasional"
        bads_daycase: "BADS: Daycase"
        bads_outpatients: "BADS: Outpatients"
        bads_outpatients_or_daycase: "BADS: Outpatients or Daycase"
      params_items:
        type: "bads"
    mitigators_op_c2c_reduction:
      activity_type: op
      mitigators_type: activity_avoidance
      y_axis_title: "% of Appointments that are Consultant to Consultant Referrals"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Appointments"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        consultant_to_consultant_reduction_adult_non-surgical: "Consultant to Consultant Reduction: Non Surgical (Adult)"
        consultant_to_consultant_reduction_adult_surgical: "Consultant to Consultant Reduction: Surgical (Adult)"
        consultant_to_consultant_reduction_child_non-surgical: "Consultant to Consultant Reduction: Non Surgical (Child)"
        consultant_to_consultant_reduction_child_surgical: "Consultant to Consultant Reduction: Surgical (Child)"
    mitigators_op_convert_tele:
      activity_type: op
      mitigators_type: efficiencies
      y_axis_title: "% of Appointments that are Face-to-Face"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Appointments"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        convert_to_tele_adult_non-surgical: "Convert to Tele: Non Surgical (Adult)"
        convert_to_tele_adult_surgical: "Convert to Tele: Surgical (Adult)"
        convert_to_tele_child_non-surgical: "Convert to Tele: Non Surgical (Child)"
        convert_to_tele_child_surgical: "Convert to Tele: Surgical (Child)"
    mitigators_op_fup_reduction:
      activity_type: op
      mitigators_type: activity_avoidance
      y_axis_title: "Followup to First Ratio"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format()
      funnel_x_title: "Number of Appointments"
      slider_scale: 1
      slider_step: 0.1
      strategy_subset:
        followup_reduction_adult_non-surgical: "Followup Reduction: Non Surgical (Adult)"
        followup_reduction_adult_surgical: "Followup Reduction: Surgical (Adult)"
        followup_reduction_child_non-surgical: "Followup Reduction: Non Surgical (Child)"
        followup_reduction_child_surgical: "Followup Reduction: Surgical (Child)"
    mitigators_aae_frequent_attenders:
      activity_type: aae
      mitigators_type: activity_avoidance
      y_axis_title: "% of Attendances that were Frequent Attenders"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Attendances"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        frequent_attenders_adult_ambulance: "Frequent Attenders: Ambulance (Adult)"
        frequent_attenders_adult_walk-in: "Frequent Attenders: Walk-in (Adult)"
        frequent_attenders_child_ambulance: "Frequent Attenders: Ambulance (Child)"
        frequent_attenders_child_walk-in: "Frequent Attenders: Walk-in (Child)"
    mitigators_aae_left_before_seen:
      activity_type: aae
      mitigators_type: activity_avoidance
      y_axis_title: "% of Attendances Where the Patient Left Before Being Seen"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Attendances"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        left_before_seen_adult_ambulance: "Left Before Seen: Ambulance (Adult)"
        left_before_seen_adult_walk-in: "Left Before Seen: Walk-in (Adult)"
        left_before_seen_child_ambulance: "Left Before Seen: Ambulance (Child)"
        left_before_seen_child_walk-in: "Left Before Seen: Walk-in (Child)"
    mitigators_aae_low_cost_discharged:
      activity_type: aae
      mitigators_type: activity_avoidance
      y_axis_title: "% of Attendances Which Were Low Cost and Patient Was Discharged Home"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Attendances"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        low_cost_discharged_adult_ambulance: "Low Cost Discharged: Ambulance (Adult)"
        low_cost_discharged_adult_walk-in: "Low Cost Discharged: Walk-in (Adult)"
        low_cost_discharged_child_ambulance: "Low Cost Discharged: Ambulance (Child)"
        low_cost_discharged_child_walk-in: "Low Cost Discharged: Walk-in (Child)"
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
