default:
  golem_name: inputs
  golem_version: 0.0.0.9000
  app_prod: no
  mitigators_config:
    mitigators_admission_avoidance:
      y_axis_title: "Indexed Directly Standardised Rate"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.001)
      funnel_x_title: "Catchment Population of Trust"
      funnel_number_type: !expr scales::comma_format()
      slider_scale: 1
      slider_step: 0.001
      strategy_subset:
        - alcohol_partially_attributable_acute
        - alcohol_partially_attributable_chronic
        - alcohol_wholly_attributable
        - ambulatory_care_conditions_acute
        - ambulatory_care_conditions_chronic
        - ambulatory_care_conditions_vaccine_preventable
        - cancelled_operations
        - eol_care_2_days
        - eol_care_3_to_14_days
        - evidence_based_interventions_ent
        - evidence_based_interventions_general_surgery
        - evidence_based_interventions_gi_surgical
        - evidence_based_interventions_msk
        - evidence_based_interventions_urology
        - evidence_based_interventions_vascular_varicose_veins
        - falls_related_admissions
        - frail_elderly_high
        - frail_elderly_intermediate
        - intentional_self_harm
        - medically_unexplained_related_admissions
        - medicines_related_admissions_explicit
        - medicines_related_admissions_implicit_anti-diabetics
        - medicines_related_admissions_implicit_benzodiasepines
        - medicines_related_admissions_implicit_diurectics
        - medicines_related_admissions_implicit_nsaids
        - obesity_related_admissions
        - raid_ae
        - readmission_within_28_days
        - smoking
        - zero_los_no_procedure_adult
        - zero_los_no_procedure_child
    mitigators_mean_los_reduction:
      y_axis_title: "Mean Length of Stay (days)"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.1)
      funnel_x_title: "Number of Admissions"
      slider_scale: 1
      slider_step: 0.1
      strategy_subset:
        - emergency_elderly
        - enhanced_recovery_bladder
        - enhanced_recovery_breast
        - enhanced_recovery_colectomy
        - enhanced_recovery_hip
        - enhanced_recovery_hysterectomy
        - enhanced_recovery_knee
        - enhanced_recovery_prostate
        - enhanced_recovery_rectum
        - excess_beddays_elective
        - excess_beddays_emergency
        - raid_ip
        - stroke_early_supported_discharge
      params_items:
        type: "all"
    mitigators_aec_los_reduction:
      y_axis_title: "% 0-Day Admissions"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Admissions"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - ambulatory_emergency_care_low
        - ambulatory_emergency_care_moderate
        - ambulatory_emergency_care_high
        - ambulatory_emergency_care_very_high
      params_items:
        type: "aec"
      param_conversion:
        absolute:
          - !expr \(r, p) rev(1 - p + r * p)
          - !expr \(r, q) rev(1 - (q - r) / (1 - r))
        relative:
          - !expr \(r, p) rev(1 - p)
          - !expr \(r, q) rev(1 - q)
      inverted: true
    mitigators_preop_los_reduction:
      y_axis_title: "Procedures with a Pre-op LoS (per 1000 operations)"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.1, scale = 1000)
      funnel_x_title: "Number of Procedures Performed"
      slider_scale: 1000
      slider_step: 0.1
      strategy_subset:
        - pre-op_los_1-day
        - pre-op_los_2-day
      params_items:
        type: "pre-op"
        pre-op_days:
          pre-op_los_1-day: 1
          pre-op_los_2-day: 2
    mitigators_bads:
      y_axis_title: "% of Procedures Performed in Target Setting"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Procedures Performed"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - bads_daycase_occasional
        - bads_daycase
        - bads_outpatients
        - bads_outpatients_or_daycase
      params_items:
        type: "bads"
        baseline_target_rate: !expr \(r) r$rate
        op_dc_split: !expr \(r) r$split
      param_conversion:
        absolute:
          - !expr \(r, p) rev(1 - p + r * p)
          - !expr \(r, q) rev(1 - (q - r) / (1 - r))
        relative:
          - !expr \(r, p) rev(1 - p)
          - !expr \(r, q) rev(1 - q)
      param_output: !expr \(r, q) rev(1 - q) * (1 - r) + r
      inverted: true
    mitigators_op_c2c_reduction:
      y_axis_title: "% of Appointments that are Consultant to Consultant Referrals"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Appointments"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - consultant_to_consultant_reduction_(adult_non-surgical)
        - consultant_to_consultant_reduction_(adult_surgical)
        - consultant_to_consultant_reduction_(child_non-surgical)
        - consultant_to_consultant_reduction_(child_surgical)
    mitigators_op_convert_tele:
      y_axis_title: "% of Appointments that are Tele Appointments"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Appointments"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - convert_to_tele_(adult_non-surgical)
        - convert_to_tele_(adult_surgical)
        - convert_to_tele_(child_non-surgical)
        - convert_to_tele_(child_surgical)
      param_conversion:
        absolute:
          - !expr \(r, p) rev(1 - p + r * p)
          - !expr \(r, q) rev(1 - (q - r) / (1 - r))
        relative:
          - !expr \(r, p) rev(1 - p)
          - !expr \(r, q) rev(1 - q)
      param_output: !expr \(r, q) rev(1 - (q - r) / (1 - r))
      inverted: true
    mitigators_op_fup_reduction:
      y_axis_title: "Followup to First Ratio"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format()
      funnel_x_title: "Number of Appointments"
      slider_scale: 1
      slider_step: 0.1
      strategy_subset:
        - followup_reduction_(adult_non-surgical)
        - followup_reduction_(adult_surgical)
        - followup_reduction_(child_non-surgical)
        - followup_reduction_(child_surgical)
    mitigators_aae_frequent_attenders:
      y_axis_title: "% of Attendances that were Frequent Attenders"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Attendances"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - frequent_attenders_(adult_ambulance)
        - frequent_attenders_(adult_walk-in)
        - frequent_attenders_(child_ambulance)
        - frequent_attenders_(child_walk-in)
    mitigators_aae_left_before_seen:
      y_axis_title: "% of Attendances Where the Patient Left Before Being Seen"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Attendances"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - left_before_seen_(adult_ambulance)
        - left_before_seen_(adult_walk-in)
        - left_before_seen_(child_ambulance)
        - left_before_seen_(child_walk-in)
    mitigators_aae_low_cost_discharged:
      y_axis_title: "% of Attendances Which Were Low Cost and Patient Was Discharged Home"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Attendances"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - low_cost_discharged_(adult_ambulance)
        - low_cost_discharged_(adult_walk-in)
        - low_cost_discharged_(child_ambulance)
        - low_cost_discharged_(child_walk-in)
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
