default:
  golem_name: inputs
  golem_version: 0.0.0.9000
  app_prod: no
  mitigators_config:
    mitigators_admission_avoidance:
      y_axis_title: "Directly Standardised Rate"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.001)
      trend_box_title: "Trend in Directly Standardised Activity Rates (DSR)"
      funnel_box_title: "Funnel Plot of DSR for Peer Trusts"
      funnel_x_title: "Catchment Population of Trust"
      boxplot_title: "Boxplot of DSRs"
      funnel_number_type: !expr scales::comma_format()
      slider_scale: 1
      slider_step: 0.001
      strategy_subset:
        - alcohol_partially_attributable_acute
        - alcohol_partially_attributable_chronic
        - alcohol_wholly_attributable
        - ambulatory_care_conditions_acute
        - ambulatory_care_conditions_chronic
        - ambulatory_care_conditions_vaccine_preventable
        - cancelled_operations
        - eol_care_2_days
        - eol_care_3_to_14_days
        - evidence_based_interventions_ent
        - evidence_based_interventions_general_surgery
        - evidence_based_interventions_gi_surgical
        - evidence_based_interventions_msk
        - evidence_based_interventions_urology
        - evidence_based_interventions_vascular_varicose_veins
        - falls_related_admissions
        - frail_elderly_high
        - frail_elderly_intermediate
        - intentional_self_harm
        - medically_unexplained_related_admissions
        - medicines_related_admissions_explicit
        - medicines_related_admissions_implicit_anti-diabetics
        - medicines_related_admissions_implicit_benzodiasepines
        - medicines_related_admissions_implicit_diurectics
        - medicines_related_admissions_implicit_nsaids
        - obesity_related_admissions
        - raid_ae
        - readmission_within_28_days
        - smoking
        - zero_los_no_procedure_adult
        - zero_los_no_procedure_child
    mitigators_mean_los_reduction:
      y_axis_title: "Mean Length of Stay (days)"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.1)
      trend_box_title: "Trend in Mean LoS"
      funnel_box_title: "Funnel Plot of Mean LoS for Peer Trusts"
      funnel_x_title: "Number of Admissions"
      boxplot_title: "Boxplot of Mean LoS"
      slider_scale: 1
      slider_step: 0.1
      strategy_subset:
        - emergency_elderly
        - enhanced_recovery_bladder
        - enhanced_recovery_breast
        - enhanced_recovery_colectomy
        - enhanced_recovery_hip
        - enhanced_recovery_hysterectomy
        - enhanced_recovery_knee
        - enhanced_recovery_prostate
        - enhanced_recovery_rectum
        - excess_beddays_elective
        - excess_beddays_emergency
        - raid_ip
        - stroke_early_supported_discharge
      params_items:
        type: "all"
    mitigators_aec_los_reduction:
      y_axis_title: "% 0-Day Admissions"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      trend_box_title: "Trend in % 0-Day Admissions"
      funnel_box_title: "Funnel Plot of % 0-Day Admissions for Peer Trusts"
      funnel_x_title: "Number of Admissions"
      boxplot_title: "Boxplot of % 0-Day Admissions"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - ambulatory_emergency_care_low
        - ambulatory_emergency_care_moderate
        - ambulatory_emergency_care_high
        - ambulatory_emergency_care_very_high
      params_items:
        type: "aec"
    mitigators_preop_los_reduction:
      y_axis_title: "Procedures with a Pre-op LoS (per 1000 operations)"
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format(accuracy = 0.1, scale = 1000)
      trend_box_title: "Trend in Procedures with a Pre-op LoS of 1 or 2 days (per 1000 operations)"
      funnel_box_title: "Funnel Plot of Pre-op LoS for Peer Trusts"
      funnel_x_title: "Number of Procedures Performed"
      boxplot_title: "Boxplot of Pre-op LoS"
      slider_scale: 1000
      slider_step: 0.1
      strategy_subset:
        - pre-op_los_1-day
        - pre-op_los_2-day
      params_items:
        type: "pre-op"
    mitigators_bads:
      y_axis_title: "% of Procedures Performed in Target Setting"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      trend_box_title: "Trend in % of Procedures Performed in Target Setting"
      funnel_box_title: "Funnel Plot of % of Procedures Performed in Target Setting for Peer Trusts"
      funnel_x_title: "Number of Procedures Performed"
      boxplot_title: "Boxplot of % of Procedures Performed in Target Setting"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - bads_daycase_occasional
        - bads_daycase
        - bads_outpatients
        - bads_outpatients_or_daycase
      params_items:
        type: "bads"
        baseline_target_rate: !expr \(r) r$rate
        op_dc_split: !expr \(r) r$split
      inverted: true
    mitigators_op_c2c_reduction:
      y_axis_title: ""
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      trend_box_title: "Trend in "
      funnel_box_title: "Funnel Plot of "
      funnel_x_title: "Number of Appointments"
      boxplot_title: "Boxplot of "
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - consultant_to_consultant_reduction_(adult_non-surgical)
        - consultant_to_consultant_reduction_(adult_surgical)
        - consultant_to_consultant_reduction_(child_non-surgical)
        - consultant_to_consultant_reduction_(child_surgical)
    mitigators_op_convert_tele:
      y_axis_title: ""
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      trend_box_title: "Trend in "
      funnel_box_title: "Funnel Plot of "
      funnel_x_title: "Number of Appointments"
      boxplot_title: "Boxplot of "
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:
        - convert_to_tele_(adult_non-surgical)
        - convert_to_tele_(adult_surgical)
        - convert_to_tele_(child_non-surgical)
        - convert_to_tele_(child_surgical)
      inverted: true
    mitigators_op_fup_reduction:
      y_axis_title: ""
      x_axis_title: "Financial Year"
      number_type: !expr scales::comma_format()
      trend_box_title: "Trend in "
      funnel_box_title: "Funnel Plot of "
      funnel_x_title: "Number of Appointments"
      boxplot_title: "Boxplot of "
      slider_scale: 1
      slider_step: 0.1
      strategy_subset:
        - followup_reduction_(adult_non-surgical)
        - followup_reduction_(adult_surgical)
        - followup_reduction_(child_non-surgical)
        - followup_reduction_(child_surgical)
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
