name: "Connect Publish (prod)"
on:
  release:
    types: [published]

jobs:
  connect-publish-prod:
    name: "Connect Publish: Production"
    runs-on: ubuntu-latest
    env:
      # these get set later
      VERSION: ""
      INPUTS_DATA_VERSION: ""

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        run: |
          VERSION=`echo ${{ github.ref_name }} | awk 'BEGIN { FS="."; } { print ""$1"-"$2; }'`
          INPUTS_DATA_VERSION=`echo $VERSION | sed 's/-/./'`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "INPUTS_DATA_VERSION=$INPUTS_DATA_VERSION" >> $GITHUB_ENV

      - name: Update manifest.json
        run: node update_manifest.js
        
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_NHP_API_KEY: ${{ secrets.NHP_API_KEY }}
          CONNECT_ENV_SET_NHP_API_URI: ${{ secrets.NHP_API_URI }}
          CONNECT_ENV_SET_NHP_ENCRYPT_KEY: ${{ secrets.NHP_ENCRYPT_KEY }}
          CONNECT_ENV_SET_NHP_INPUTS_DATA_VERSION: ${{ env.INPUTS_DATA_VERSION }}
          CONNECT_ENV_SET_NHP_OUTPUTS_URI: ${{ secrets.NHP_OUTPUTS_URI }}
          CONNECT_ENV_SET_GOLEM_CONFIG_ACTIVE: "production"
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: logged_in
          force: true
          dir: .:inputs
          namespace: nhp/${{ env.VERSION }}
