name: "Connect Publish (dev)"
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-production:
    name: "Publish (to production server)"
    uses: ./.github/workflows/connect-publish-manual.yaml
    with:
      namespace: "dev"
      inputs_data_version: "dev"
      environment: "production"
    secrets: inherit
        
  publish-new-production:
    name: "Publish (to new production server)"
    uses: ./.github/workflows/connect-publish-manual.yaml
    with:
      namespace: "dev"
      inputs_data_version: "dev"
      environment: "new-production"
    secrets: inherit