name: "Connect Publish (manual)"
on:
  workflow_dispatch:
    inputs:
      namespace:
        required: true
        type: string
      inputs_data_version:
        required: true
        type: string

jobs:
  connect-publish-manual:
    name: "Connect Publish: Manual"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update manifest.json
        run: node update_manifest.js

      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_NHP_API_KEY: ${{ secrets.NHP_API_KEY }}
          CONNECT_ENV_SET_NHP_API_URI: ${{ secrets.NHP_API_URI }}
          CONNECT_ENV_SET_NHP_ENCRYPT_KEY: ${{ secrets.NHP_ENCRYPT_KEY }}
          CONNECT_ENV_SET_NHP_INPUTS_DATA_VERSION: ${{ inputs.inputs_data_version }}
          CONNECT_ENV_SET_NHP_OUTPUTS_URI: ${{ secrets.NHP_OUTPUTS_URI }}
          CONNECT_ENV_SET_GOLEM_CONFIG_ACTIVE: "production"
        with:
          url: ${{ secrets.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: acl
          force: true
          dir: .:inputs
          namespace: nhp/${{ inputs.namespace }}